/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as CSlugAuthRouteImport } from './routes/c.$slug.auth'
import { Route as CSlugAppRouteImport } from './routes/c.$slug._app'
import { Route as ApiStorageDeleteRouteImport } from './routes/api/storage/delete'
import { Route as CSlugAppTasksRouteImport } from './routes/c.$slug._app.tasks'
import { Route as CSlugAppStockRouteImport } from './routes/c.$slug._app.stock'
import { Route as CSlugAppSettingsRouteImport } from './routes/c.$slug._app.settings'
import { Route as CSlugAppReportsRouteImport } from './routes/c.$slug._app.reports'
import { Route as CSlugAppPurchaseRouteImport } from './routes/c.$slug._app.purchase'
import { Route as CSlugAppProjectsRouteImport } from './routes/c.$slug._app.projects'
import { Route as CSlugAppLeadsRouteImport } from './routes/c.$slug._app.leads'
import { Route as CSlugAppInvoicingRouteImport } from './routes/c.$slug._app.invoicing'
import { Route as CSlugAppExpensesRouteImport } from './routes/c.$slug._app.expenses'
import { Route as CSlugAppEmployeesRouteImport } from './routes/c.$slug._app.employees'
import { Route as CSlugAppDepartmentsRouteImport } from './routes/c.$slug._app.departments'
import { Route as CSlugAppDashboardRouteImport } from './routes/c.$slug._app.dashboard'
import { Route as CSlugAppClientsRouteImport } from './routes/c.$slug._app.clients'
import { Route as CSlugAppAccountsRouteImport } from './routes/c.$slug._app.accounts'
import { Route as CSlugAppStockIndexRouteImport } from './routes/c.$slug._app.stock.index'
import { Route as CSlugAppSettingsIndexRouteImport } from './routes/c.$slug._app.settings.index'
import { Route as CSlugAppReportsIndexRouteImport } from './routes/c.$slug._app.reports.index'
import { Route as CSlugAppPurchaseIndexRouteImport } from './routes/c.$slug._app.purchase.index'
import { Route as CSlugAppProjectsIndexRouteImport } from './routes/c.$slug._app.projects.index'
import { Route as CSlugAppLeadsIndexRouteImport } from './routes/c.$slug._app.leads.index'
import { Route as CSlugAppInvoicingIndexRouteImport } from './routes/c.$slug._app.invoicing.index'
import { Route as CSlugAppDepartmentsIndexRouteImport } from './routes/c.$slug._app.departments.index'
import { Route as CSlugAppClientsIndexRouteImport } from './routes/c.$slug._app.clients.index'
import { Route as CSlugAppAccountsIndexRouteImport } from './routes/c.$slug._app.accounts.index'
import { Route as CSlugAppStockMovementsRouteImport } from './routes/c.$slug._app.stock.movements'
import { Route as CSlugAppStockItemsRouteImport } from './routes/c.$slug._app.stock.items'
import { Route as CSlugAppStockBalanceRouteImport } from './routes/c.$slug._app.stock.balance'
import { Route as CSlugAppSettingsWorkflowRouteImport } from './routes/c.$slug._app.settings.workflow'
import { Route as CSlugAppSettingsStockRouteImport } from './routes/c.$slug._app.settings.stock'
import { Route as CSlugAppSettingsRolesRouteImport } from './routes/c.$slug._app.settings.roles'
import { Route as CSlugAppSettingsProjectTemplatesRouteImport } from './routes/c.$slug._app.settings.project-templates'
import { Route as CSlugAppSettingsInvoicingRouteImport } from './routes/c.$slug._app.settings.invoicing'
import { Route as CSlugAppSettingsFieldsRouteImport } from './routes/c.$slug._app.settings.fields'
import { Route as CSlugAppSettingsDepartmentsRouteImport } from './routes/c.$slug._app.settings.departments'
import { Route as CSlugAppSettingsCompanyRouteImport } from './routes/c.$slug._app.settings.company'
import { Route as CSlugAppSettingsAuditRouteImport } from './routes/c.$slug._app.settings.audit'
import { Route as CSlugAppSettingsAppearanceRouteImport } from './routes/c.$slug._app.settings.appearance'
import { Route as CSlugAppReportsTasksRouteImport } from './routes/c.$slug._app.reports.tasks'
import { Route as CSlugAppReportsProjectsRouteImport } from './routes/c.$slug._app.reports.projects'
import { Route as CSlugAppReportsLeadsRouteImport } from './routes/c.$slug._app.reports.leads'
import { Route as CSlugAppReportsEmployeesRouteImport } from './routes/c.$slug._app.reports.employees'
import { Route as CSlugAppReportsDepartmentsRouteImport } from './routes/c.$slug._app.reports.departments'
import { Route as CSlugAppReportsAccountsRouteImport } from './routes/c.$slug._app.reports.accounts'
import { Route as CSlugAppPurchaseSuppliersRouteImport } from './routes/c.$slug._app.purchase.suppliers'
import { Route as CSlugAppPurchasePendingRouteImport } from './routes/c.$slug._app.purchase.pending'
import { Route as CSlugAppPurchasePaymentsRouteImport } from './routes/c.$slug._app.purchase.payments'
import { Route as CSlugAppPurchaseOrdersRouteImport } from './routes/c.$slug._app.purchase.orders'
import { Route as CSlugAppProjectsProjectIdRouteImport } from './routes/c.$slug._app.projects.$projectId'
import { Route as CSlugAppLeadsLeadIdRouteImport } from './routes/c.$slug._app.leads.$leadId'
import { Route as CSlugAppInvoicingQuotationsRouteImport } from './routes/c.$slug._app.invoicing.quotations'
import { Route as CSlugAppInvoicingPendingRouteImport } from './routes/c.$slug._app.invoicing.pending'
import { Route as CSlugAppInvoicingPaymentsRouteImport } from './routes/c.$slug._app.invoicing.payments'
import { Route as CSlugAppInvoicingInvoicesRouteImport } from './routes/c.$slug._app.invoicing.invoices'
import { Route as CSlugAppDepartmentsDeptIdRouteImport } from './routes/c.$slug._app.departments.$deptId'
import { Route as CSlugAppClientsClientIdRouteImport } from './routes/c.$slug._app.clients.$clientId'
import { Route as CSlugAppAccountsPendingRouteImport } from './routes/c.$slug._app.accounts.pending'
import { Route as CSlugAppAccountsLedgerRouteImport } from './routes/c.$slug._app.accounts.ledger'
import { Route as CSlugAppAccountsIncomeRouteImport } from './routes/c.$slug._app.accounts.income'
import { Route as CSlugAppAccountsExpensesRouteImport } from './routes/c.$slug._app.accounts.expenses'
import { Route as CSlugAppAccountsBookRouteImport } from './routes/c.$slug._app.accounts.book'
import { Route as ApiPublicCSlugManifestDotwebmanifestRouteImport } from './routes/api/public/c.$slug.manifest[.]webmanifest'
import { Route as ApiPublicCSlugLogoRouteImport } from './routes/api/public/c.$slug.logo'
import { Route as CSlugAppPurchaseSuppliersSupplierIdRouteImport } from './routes/c.$slug._app.purchase.suppliers.$supplierId'
import { Route as CSlugAppLeadsStageStageRouteImport } from './routes/c.$slug._app.leads.stage.$stage'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugAuthRoute = CSlugAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugAppRoute = CSlugAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => CSlugRoute,
} as any)
const ApiStorageDeleteRoute = ApiStorageDeleteRouteImport.update({
  id: '/api/storage/delete',
  path: '/api/storage/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugAppTasksRoute = CSlugAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppStockRoute = CSlugAppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppSettingsRoute = CSlugAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppReportsRoute = CSlugAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppPurchaseRoute = CSlugAppPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppProjectsRoute = CSlugAppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppLeadsRoute = CSlugAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppInvoicingRoute = CSlugAppInvoicingRouteImport.update({
  id: '/invoicing',
  path: '/invoicing',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppExpensesRoute = CSlugAppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppEmployeesRoute = CSlugAppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppDepartmentsRoute = CSlugAppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppDashboardRoute = CSlugAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppClientsRoute = CSlugAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppAccountsRoute = CSlugAppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => CSlugAppRoute,
} as any)
const CSlugAppStockIndexRoute = CSlugAppStockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugAppStockRoute,
} as any)
const CSlugAppSettingsIndexRoute = CSlugAppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugAppSettingsRoute,
} as any)
const CSlugAppReportsIndexRoute = CSlugAppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugAppReportsRoute,
} as any)
const CSlugAppPurchaseIndexRoute = CSlugAppPurchaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugAppPurchaseRoute,
} as any)
const CSlugAppProjectsIndexRoute = CSlugAppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugAppProjectsRoute,
} as any)
const CSlugAppLeadsIndexRoute = CSlugAppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugAppLeadsRoute,
} as any)
const CSlugAppInvoicingIndexRoute = CSlugAppInvoicingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugAppInvoicingRoute,
} as any)
const CSlugAppDepartmentsIndexRoute =
  CSlugAppDepartmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CSlugAppDepartmentsRoute,
  } as any)
const CSlugAppClientsIndexRoute = CSlugAppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugAppClientsRoute,
} as any)
const CSlugAppAccountsIndexRoute = CSlugAppAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugAppAccountsRoute,
} as any)
const CSlugAppStockMovementsRoute = CSlugAppStockMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => CSlugAppStockRoute,
} as any)
const CSlugAppStockItemsRoute = CSlugAppStockItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => CSlugAppStockRoute,
} as any)
const CSlugAppStockBalanceRoute = CSlugAppStockBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => CSlugAppStockRoute,
} as any)
const CSlugAppSettingsWorkflowRoute =
  CSlugAppSettingsWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => CSlugAppSettingsRoute,
  } as any)
const CSlugAppSettingsStockRoute = CSlugAppSettingsStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => CSlugAppSettingsRoute,
} as any)
const CSlugAppSettingsRolesRoute = CSlugAppSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => CSlugAppSettingsRoute,
} as any)
const CSlugAppSettingsProjectTemplatesRoute =
  CSlugAppSettingsProjectTemplatesRouteImport.update({
    id: '/project-templates',
    path: '/project-templates',
    getParentRoute: () => CSlugAppSettingsRoute,
  } as any)
const CSlugAppSettingsInvoicingRoute =
  CSlugAppSettingsInvoicingRouteImport.update({
    id: '/invoicing',
    path: '/invoicing',
    getParentRoute: () => CSlugAppSettingsRoute,
  } as any)
const CSlugAppSettingsFieldsRoute = CSlugAppSettingsFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => CSlugAppSettingsRoute,
} as any)
const CSlugAppSettingsDepartmentsRoute =
  CSlugAppSettingsDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => CSlugAppSettingsRoute,
  } as any)
const CSlugAppSettingsCompanyRoute = CSlugAppSettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => CSlugAppSettingsRoute,
} as any)
const CSlugAppSettingsAuditRoute = CSlugAppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => CSlugAppSettingsRoute,
} as any)
const CSlugAppSettingsAppearanceRoute =
  CSlugAppSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => CSlugAppSettingsRoute,
  } as any)
const CSlugAppReportsTasksRoute = CSlugAppReportsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CSlugAppReportsRoute,
} as any)
const CSlugAppReportsProjectsRoute = CSlugAppReportsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => CSlugAppReportsRoute,
} as any)
const CSlugAppReportsLeadsRoute = CSlugAppReportsLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CSlugAppReportsRoute,
} as any)
const CSlugAppReportsEmployeesRoute =
  CSlugAppReportsEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => CSlugAppReportsRoute,
  } as any)
const CSlugAppReportsDepartmentsRoute =
  CSlugAppReportsDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => CSlugAppReportsRoute,
  } as any)
const CSlugAppReportsAccountsRoute = CSlugAppReportsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => CSlugAppReportsRoute,
} as any)
const CSlugAppPurchaseSuppliersRoute =
  CSlugAppPurchaseSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => CSlugAppPurchaseRoute,
  } as any)
const CSlugAppPurchasePendingRoute = CSlugAppPurchasePendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => CSlugAppPurchaseRoute,
} as any)
const CSlugAppPurchasePaymentsRoute =
  CSlugAppPurchasePaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => CSlugAppPurchaseRoute,
  } as any)
const CSlugAppPurchaseOrdersRoute = CSlugAppPurchaseOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CSlugAppPurchaseRoute,
} as any)
const CSlugAppProjectsProjectIdRoute =
  CSlugAppProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => CSlugAppProjectsRoute,
  } as any)
const CSlugAppLeadsLeadIdRoute = CSlugAppLeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => CSlugAppLeadsRoute,
} as any)
const CSlugAppInvoicingQuotationsRoute =
  CSlugAppInvoicingQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => CSlugAppInvoicingRoute,
  } as any)
const CSlugAppInvoicingPendingRoute =
  CSlugAppInvoicingPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => CSlugAppInvoicingRoute,
  } as any)
const CSlugAppInvoicingPaymentsRoute =
  CSlugAppInvoicingPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => CSlugAppInvoicingRoute,
  } as any)
const CSlugAppInvoicingInvoicesRoute =
  CSlugAppInvoicingInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => CSlugAppInvoicingRoute,
  } as any)
const CSlugAppDepartmentsDeptIdRoute =
  CSlugAppDepartmentsDeptIdRouteImport.update({
    id: '/$deptId',
    path: '/$deptId',
    getParentRoute: () => CSlugAppDepartmentsRoute,
  } as any)
const CSlugAppClientsClientIdRoute = CSlugAppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CSlugAppClientsRoute,
} as any)
const CSlugAppAccountsPendingRoute = CSlugAppAccountsPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => CSlugAppAccountsRoute,
} as any)
const CSlugAppAccountsLedgerRoute = CSlugAppAccountsLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => CSlugAppAccountsRoute,
} as any)
const CSlugAppAccountsIncomeRoute = CSlugAppAccountsIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => CSlugAppAccountsRoute,
} as any)
const CSlugAppAccountsExpensesRoute =
  CSlugAppAccountsExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => CSlugAppAccountsRoute,
  } as any)
const CSlugAppAccountsBookRoute = CSlugAppAccountsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => CSlugAppAccountsRoute,
} as any)
const ApiPublicCSlugManifestDotwebmanifestRoute =
  ApiPublicCSlugManifestDotwebmanifestRouteImport.update({
    id: '/api/public/c/$slug/manifest.webmanifest',
    path: '/api/public/c/$slug/manifest.webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCSlugLogoRoute = ApiPublicCSlugLogoRouteImport.update({
  id: '/api/public/c/$slug/logo',
  path: '/api/public/c/$slug/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugAppPurchaseSuppliersSupplierIdRoute =
  CSlugAppPurchaseSuppliersSupplierIdRouteImport.update({
    id: '/$supplierId',
    path: '/$supplierId',
    getParentRoute: () => CSlugAppPurchaseSuppliersRoute,
  } as any)
const CSlugAppLeadsStageStageRoute = CSlugAppLeadsStageStageRouteImport.update({
  id: '/stage/$stage',
  path: '/stage/$stage',
  getParentRoute: () => CSlugAppLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/storage/delete': typeof ApiStorageDeleteRoute
  '/c/$slug/auth': typeof CSlugAuthRoute
  '/c/$slug/accounts': typeof CSlugAppAccountsRouteWithChildren
  '/c/$slug/clients': typeof CSlugAppClientsRouteWithChildren
  '/c/$slug/dashboard': typeof CSlugAppDashboardRoute
  '/c/$slug/departments': typeof CSlugAppDepartmentsRouteWithChildren
  '/c/$slug/employees': typeof CSlugAppEmployeesRoute
  '/c/$slug/expenses': typeof CSlugAppExpensesRoute
  '/c/$slug/invoicing': typeof CSlugAppInvoicingRouteWithChildren
  '/c/$slug/leads': typeof CSlugAppLeadsRouteWithChildren
  '/c/$slug/projects': typeof CSlugAppProjectsRouteWithChildren
  '/c/$slug/purchase': typeof CSlugAppPurchaseRouteWithChildren
  '/c/$slug/reports': typeof CSlugAppReportsRouteWithChildren
  '/c/$slug/settings': typeof CSlugAppSettingsRouteWithChildren
  '/c/$slug/stock': typeof CSlugAppStockRouteWithChildren
  '/c/$slug/tasks': typeof CSlugAppTasksRoute
  '/api/public/c/$slug/logo': typeof ApiPublicCSlugLogoRoute
  '/api/public/c/$slug/manifest.webmanifest': typeof ApiPublicCSlugManifestDotwebmanifestRoute
  '/c/$slug/accounts/book': typeof CSlugAppAccountsBookRoute
  '/c/$slug/accounts/expenses': typeof CSlugAppAccountsExpensesRoute
  '/c/$slug/accounts/income': typeof CSlugAppAccountsIncomeRoute
  '/c/$slug/accounts/ledger': typeof CSlugAppAccountsLedgerRoute
  '/c/$slug/accounts/pending': typeof CSlugAppAccountsPendingRoute
  '/c/$slug/clients/$clientId': typeof CSlugAppClientsClientIdRoute
  '/c/$slug/departments/$deptId': typeof CSlugAppDepartmentsDeptIdRoute
  '/c/$slug/invoicing/invoices': typeof CSlugAppInvoicingInvoicesRoute
  '/c/$slug/invoicing/payments': typeof CSlugAppInvoicingPaymentsRoute
  '/c/$slug/invoicing/pending': typeof CSlugAppInvoicingPendingRoute
  '/c/$slug/invoicing/quotations': typeof CSlugAppInvoicingQuotationsRoute
  '/c/$slug/leads/$leadId': typeof CSlugAppLeadsLeadIdRoute
  '/c/$slug/projects/$projectId': typeof CSlugAppProjectsProjectIdRoute
  '/c/$slug/purchase/orders': typeof CSlugAppPurchaseOrdersRoute
  '/c/$slug/purchase/payments': typeof CSlugAppPurchasePaymentsRoute
  '/c/$slug/purchase/pending': typeof CSlugAppPurchasePendingRoute
  '/c/$slug/purchase/suppliers': typeof CSlugAppPurchaseSuppliersRouteWithChildren
  '/c/$slug/reports/accounts': typeof CSlugAppReportsAccountsRoute
  '/c/$slug/reports/departments': typeof CSlugAppReportsDepartmentsRoute
  '/c/$slug/reports/employees': typeof CSlugAppReportsEmployeesRoute
  '/c/$slug/reports/leads': typeof CSlugAppReportsLeadsRoute
  '/c/$slug/reports/projects': typeof CSlugAppReportsProjectsRoute
  '/c/$slug/reports/tasks': typeof CSlugAppReportsTasksRoute
  '/c/$slug/settings/appearance': typeof CSlugAppSettingsAppearanceRoute
  '/c/$slug/settings/audit': typeof CSlugAppSettingsAuditRoute
  '/c/$slug/settings/company': typeof CSlugAppSettingsCompanyRoute
  '/c/$slug/settings/departments': typeof CSlugAppSettingsDepartmentsRoute
  '/c/$slug/settings/fields': typeof CSlugAppSettingsFieldsRoute
  '/c/$slug/settings/invoicing': typeof CSlugAppSettingsInvoicingRoute
  '/c/$slug/settings/project-templates': typeof CSlugAppSettingsProjectTemplatesRoute
  '/c/$slug/settings/roles': typeof CSlugAppSettingsRolesRoute
  '/c/$slug/settings/stock': typeof CSlugAppSettingsStockRoute
  '/c/$slug/settings/workflow': typeof CSlugAppSettingsWorkflowRoute
  '/c/$slug/stock/balance': typeof CSlugAppStockBalanceRoute
  '/c/$slug/stock/items': typeof CSlugAppStockItemsRoute
  '/c/$slug/stock/movements': typeof CSlugAppStockMovementsRoute
  '/c/$slug/accounts/': typeof CSlugAppAccountsIndexRoute
  '/c/$slug/clients/': typeof CSlugAppClientsIndexRoute
  '/c/$slug/departments/': typeof CSlugAppDepartmentsIndexRoute
  '/c/$slug/invoicing/': typeof CSlugAppInvoicingIndexRoute
  '/c/$slug/leads/': typeof CSlugAppLeadsIndexRoute
  '/c/$slug/projects/': typeof CSlugAppProjectsIndexRoute
  '/c/$slug/purchase/': typeof CSlugAppPurchaseIndexRoute
  '/c/$slug/reports/': typeof CSlugAppReportsIndexRoute
  '/c/$slug/settings/': typeof CSlugAppSettingsIndexRoute
  '/c/$slug/stock/': typeof CSlugAppStockIndexRoute
  '/c/$slug/leads/stage/$stage': typeof CSlugAppLeadsStageStageRoute
  '/c/$slug/purchase/suppliers/$supplierId': typeof CSlugAppPurchaseSuppliersSupplierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/api/storage/delete': typeof ApiStorageDeleteRoute
  '/c/$slug/auth': typeof CSlugAuthRoute
  '/c/$slug/dashboard': typeof CSlugAppDashboardRoute
  '/c/$slug/employees': typeof CSlugAppEmployeesRoute
  '/c/$slug/expenses': typeof CSlugAppExpensesRoute
  '/c/$slug/tasks': typeof CSlugAppTasksRoute
  '/api/public/c/$slug/logo': typeof ApiPublicCSlugLogoRoute
  '/api/public/c/$slug/manifest.webmanifest': typeof ApiPublicCSlugManifestDotwebmanifestRoute
  '/c/$slug/accounts/book': typeof CSlugAppAccountsBookRoute
  '/c/$slug/accounts/expenses': typeof CSlugAppAccountsExpensesRoute
  '/c/$slug/accounts/income': typeof CSlugAppAccountsIncomeRoute
  '/c/$slug/accounts/ledger': typeof CSlugAppAccountsLedgerRoute
  '/c/$slug/accounts/pending': typeof CSlugAppAccountsPendingRoute
  '/c/$slug/clients/$clientId': typeof CSlugAppClientsClientIdRoute
  '/c/$slug/departments/$deptId': typeof CSlugAppDepartmentsDeptIdRoute
  '/c/$slug/invoicing/invoices': typeof CSlugAppInvoicingInvoicesRoute
  '/c/$slug/invoicing/payments': typeof CSlugAppInvoicingPaymentsRoute
  '/c/$slug/invoicing/pending': typeof CSlugAppInvoicingPendingRoute
  '/c/$slug/invoicing/quotations': typeof CSlugAppInvoicingQuotationsRoute
  '/c/$slug/leads/$leadId': typeof CSlugAppLeadsLeadIdRoute
  '/c/$slug/projects/$projectId': typeof CSlugAppProjectsProjectIdRoute
  '/c/$slug/purchase/orders': typeof CSlugAppPurchaseOrdersRoute
  '/c/$slug/purchase/payments': typeof CSlugAppPurchasePaymentsRoute
  '/c/$slug/purchase/pending': typeof CSlugAppPurchasePendingRoute
  '/c/$slug/purchase/suppliers': typeof CSlugAppPurchaseSuppliersRouteWithChildren
  '/c/$slug/reports/accounts': typeof CSlugAppReportsAccountsRoute
  '/c/$slug/reports/departments': typeof CSlugAppReportsDepartmentsRoute
  '/c/$slug/reports/employees': typeof CSlugAppReportsEmployeesRoute
  '/c/$slug/reports/leads': typeof CSlugAppReportsLeadsRoute
  '/c/$slug/reports/projects': typeof CSlugAppReportsProjectsRoute
  '/c/$slug/reports/tasks': typeof CSlugAppReportsTasksRoute
  '/c/$slug/settings/appearance': typeof CSlugAppSettingsAppearanceRoute
  '/c/$slug/settings/audit': typeof CSlugAppSettingsAuditRoute
  '/c/$slug/settings/company': typeof CSlugAppSettingsCompanyRoute
  '/c/$slug/settings/departments': typeof CSlugAppSettingsDepartmentsRoute
  '/c/$slug/settings/fields': typeof CSlugAppSettingsFieldsRoute
  '/c/$slug/settings/invoicing': typeof CSlugAppSettingsInvoicingRoute
  '/c/$slug/settings/project-templates': typeof CSlugAppSettingsProjectTemplatesRoute
  '/c/$slug/settings/roles': typeof CSlugAppSettingsRolesRoute
  '/c/$slug/settings/stock': typeof CSlugAppSettingsStockRoute
  '/c/$slug/settings/workflow': typeof CSlugAppSettingsWorkflowRoute
  '/c/$slug/stock/balance': typeof CSlugAppStockBalanceRoute
  '/c/$slug/stock/items': typeof CSlugAppStockItemsRoute
  '/c/$slug/stock/movements': typeof CSlugAppStockMovementsRoute
  '/c/$slug/accounts': typeof CSlugAppAccountsIndexRoute
  '/c/$slug/clients': typeof CSlugAppClientsIndexRoute
  '/c/$slug/departments': typeof CSlugAppDepartmentsIndexRoute
  '/c/$slug/invoicing': typeof CSlugAppInvoicingIndexRoute
  '/c/$slug/leads': typeof CSlugAppLeadsIndexRoute
  '/c/$slug/projects': typeof CSlugAppProjectsIndexRoute
  '/c/$slug/purchase': typeof CSlugAppPurchaseIndexRoute
  '/c/$slug/reports': typeof CSlugAppReportsIndexRoute
  '/c/$slug/settings': typeof CSlugAppSettingsIndexRoute
  '/c/$slug/stock': typeof CSlugAppStockIndexRoute
  '/c/$slug/leads/stage/$stage': typeof CSlugAppLeadsStageStageRoute
  '/c/$slug/purchase/suppliers/$supplierId': typeof CSlugAppPurchaseSuppliersSupplierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/storage/delete': typeof ApiStorageDeleteRoute
  '/c/$slug/_app': typeof CSlugAppRouteWithChildren
  '/c/$slug/auth': typeof CSlugAuthRoute
  '/c/$slug/_app/accounts': typeof CSlugAppAccountsRouteWithChildren
  '/c/$slug/_app/clients': typeof CSlugAppClientsRouteWithChildren
  '/c/$slug/_app/dashboard': typeof CSlugAppDashboardRoute
  '/c/$slug/_app/departments': typeof CSlugAppDepartmentsRouteWithChildren
  '/c/$slug/_app/employees': typeof CSlugAppEmployeesRoute
  '/c/$slug/_app/expenses': typeof CSlugAppExpensesRoute
  '/c/$slug/_app/invoicing': typeof CSlugAppInvoicingRouteWithChildren
  '/c/$slug/_app/leads': typeof CSlugAppLeadsRouteWithChildren
  '/c/$slug/_app/projects': typeof CSlugAppProjectsRouteWithChildren
  '/c/$slug/_app/purchase': typeof CSlugAppPurchaseRouteWithChildren
  '/c/$slug/_app/reports': typeof CSlugAppReportsRouteWithChildren
  '/c/$slug/_app/settings': typeof CSlugAppSettingsRouteWithChildren
  '/c/$slug/_app/stock': typeof CSlugAppStockRouteWithChildren
  '/c/$slug/_app/tasks': typeof CSlugAppTasksRoute
  '/api/public/c/$slug/logo': typeof ApiPublicCSlugLogoRoute
  '/api/public/c/$slug/manifest.webmanifest': typeof ApiPublicCSlugManifestDotwebmanifestRoute
  '/c/$slug/_app/accounts/book': typeof CSlugAppAccountsBookRoute
  '/c/$slug/_app/accounts/expenses': typeof CSlugAppAccountsExpensesRoute
  '/c/$slug/_app/accounts/income': typeof CSlugAppAccountsIncomeRoute
  '/c/$slug/_app/accounts/ledger': typeof CSlugAppAccountsLedgerRoute
  '/c/$slug/_app/accounts/pending': typeof CSlugAppAccountsPendingRoute
  '/c/$slug/_app/clients/$clientId': typeof CSlugAppClientsClientIdRoute
  '/c/$slug/_app/departments/$deptId': typeof CSlugAppDepartmentsDeptIdRoute
  '/c/$slug/_app/invoicing/invoices': typeof CSlugAppInvoicingInvoicesRoute
  '/c/$slug/_app/invoicing/payments': typeof CSlugAppInvoicingPaymentsRoute
  '/c/$slug/_app/invoicing/pending': typeof CSlugAppInvoicingPendingRoute
  '/c/$slug/_app/invoicing/quotations': typeof CSlugAppInvoicingQuotationsRoute
  '/c/$slug/_app/leads/$leadId': typeof CSlugAppLeadsLeadIdRoute
  '/c/$slug/_app/projects/$projectId': typeof CSlugAppProjectsProjectIdRoute
  '/c/$slug/_app/purchase/orders': typeof CSlugAppPurchaseOrdersRoute
  '/c/$slug/_app/purchase/payments': typeof CSlugAppPurchasePaymentsRoute
  '/c/$slug/_app/purchase/pending': typeof CSlugAppPurchasePendingRoute
  '/c/$slug/_app/purchase/suppliers': typeof CSlugAppPurchaseSuppliersRouteWithChildren
  '/c/$slug/_app/reports/accounts': typeof CSlugAppReportsAccountsRoute
  '/c/$slug/_app/reports/departments': typeof CSlugAppReportsDepartmentsRoute
  '/c/$slug/_app/reports/employees': typeof CSlugAppReportsEmployeesRoute
  '/c/$slug/_app/reports/leads': typeof CSlugAppReportsLeadsRoute
  '/c/$slug/_app/reports/projects': typeof CSlugAppReportsProjectsRoute
  '/c/$slug/_app/reports/tasks': typeof CSlugAppReportsTasksRoute
  '/c/$slug/_app/settings/appearance': typeof CSlugAppSettingsAppearanceRoute
  '/c/$slug/_app/settings/audit': typeof CSlugAppSettingsAuditRoute
  '/c/$slug/_app/settings/company': typeof CSlugAppSettingsCompanyRoute
  '/c/$slug/_app/settings/departments': typeof CSlugAppSettingsDepartmentsRoute
  '/c/$slug/_app/settings/fields': typeof CSlugAppSettingsFieldsRoute
  '/c/$slug/_app/settings/invoicing': typeof CSlugAppSettingsInvoicingRoute
  '/c/$slug/_app/settings/project-templates': typeof CSlugAppSettingsProjectTemplatesRoute
  '/c/$slug/_app/settings/roles': typeof CSlugAppSettingsRolesRoute
  '/c/$slug/_app/settings/stock': typeof CSlugAppSettingsStockRoute
  '/c/$slug/_app/settings/workflow': typeof CSlugAppSettingsWorkflowRoute
  '/c/$slug/_app/stock/balance': typeof CSlugAppStockBalanceRoute
  '/c/$slug/_app/stock/items': typeof CSlugAppStockItemsRoute
  '/c/$slug/_app/stock/movements': typeof CSlugAppStockMovementsRoute
  '/c/$slug/_app/accounts/': typeof CSlugAppAccountsIndexRoute
  '/c/$slug/_app/clients/': typeof CSlugAppClientsIndexRoute
  '/c/$slug/_app/departments/': typeof CSlugAppDepartmentsIndexRoute
  '/c/$slug/_app/invoicing/': typeof CSlugAppInvoicingIndexRoute
  '/c/$slug/_app/leads/': typeof CSlugAppLeadsIndexRoute
  '/c/$slug/_app/projects/': typeof CSlugAppProjectsIndexRoute
  '/c/$slug/_app/purchase/': typeof CSlugAppPurchaseIndexRoute
  '/c/$slug/_app/reports/': typeof CSlugAppReportsIndexRoute
  '/c/$slug/_app/settings/': typeof CSlugAppSettingsIndexRoute
  '/c/$slug/_app/stock/': typeof CSlugAppStockIndexRoute
  '/c/$slug/_app/leads/stage/$stage': typeof CSlugAppLeadsStageStageRoute
  '/c/$slug/_app/purchase/suppliers/$supplierId': typeof CSlugAppPurchaseSuppliersSupplierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/c/$slug'
    | '/admin/'
    | '/api/storage/delete'
    | '/c/$slug/auth'
    | '/c/$slug/accounts'
    | '/c/$slug/clients'
    | '/c/$slug/dashboard'
    | '/c/$slug/departments'
    | '/c/$slug/employees'
    | '/c/$slug/expenses'
    | '/c/$slug/invoicing'
    | '/c/$slug/leads'
    | '/c/$slug/projects'
    | '/c/$slug/purchase'
    | '/c/$slug/reports'
    | '/c/$slug/settings'
    | '/c/$slug/stock'
    | '/c/$slug/tasks'
    | '/api/public/c/$slug/logo'
    | '/api/public/c/$slug/manifest.webmanifest'
    | '/c/$slug/accounts/book'
    | '/c/$slug/accounts/expenses'
    | '/c/$slug/accounts/income'
    | '/c/$slug/accounts/ledger'
    | '/c/$slug/accounts/pending'
    | '/c/$slug/clients/$clientId'
    | '/c/$slug/departments/$deptId'
    | '/c/$slug/invoicing/invoices'
    | '/c/$slug/invoicing/payments'
    | '/c/$slug/invoicing/pending'
    | '/c/$slug/invoicing/quotations'
    | '/c/$slug/leads/$leadId'
    | '/c/$slug/projects/$projectId'
    | '/c/$slug/purchase/orders'
    | '/c/$slug/purchase/payments'
    | '/c/$slug/purchase/pending'
    | '/c/$slug/purchase/suppliers'
    | '/c/$slug/reports/accounts'
    | '/c/$slug/reports/departments'
    | '/c/$slug/reports/employees'
    | '/c/$slug/reports/leads'
    | '/c/$slug/reports/projects'
    | '/c/$slug/reports/tasks'
    | '/c/$slug/settings/appearance'
    | '/c/$slug/settings/audit'
    | '/c/$slug/settings/company'
    | '/c/$slug/settings/departments'
    | '/c/$slug/settings/fields'
    | '/c/$slug/settings/invoicing'
    | '/c/$slug/settings/project-templates'
    | '/c/$slug/settings/roles'
    | '/c/$slug/settings/stock'
    | '/c/$slug/settings/workflow'
    | '/c/$slug/stock/balance'
    | '/c/$slug/stock/items'
    | '/c/$slug/stock/movements'
    | '/c/$slug/accounts/'
    | '/c/$slug/clients/'
    | '/c/$slug/departments/'
    | '/c/$slug/invoicing/'
    | '/c/$slug/leads/'
    | '/c/$slug/projects/'
    | '/c/$slug/purchase/'
    | '/c/$slug/reports/'
    | '/c/$slug/settings/'
    | '/c/$slug/stock/'
    | '/c/$slug/leads/stage/$stage'
    | '/c/$slug/purchase/suppliers/$supplierId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/c/$slug'
    | '/admin'
    | '/api/storage/delete'
    | '/c/$slug/auth'
    | '/c/$slug/dashboard'
    | '/c/$slug/employees'
    | '/c/$slug/expenses'
    | '/c/$slug/tasks'
    | '/api/public/c/$slug/logo'
    | '/api/public/c/$slug/manifest.webmanifest'
    | '/c/$slug/accounts/book'
    | '/c/$slug/accounts/expenses'
    | '/c/$slug/accounts/income'
    | '/c/$slug/accounts/ledger'
    | '/c/$slug/accounts/pending'
    | '/c/$slug/clients/$clientId'
    | '/c/$slug/departments/$deptId'
    | '/c/$slug/invoicing/invoices'
    | '/c/$slug/invoicing/payments'
    | '/c/$slug/invoicing/pending'
    | '/c/$slug/invoicing/quotations'
    | '/c/$slug/leads/$leadId'
    | '/c/$slug/projects/$projectId'
    | '/c/$slug/purchase/orders'
    | '/c/$slug/purchase/payments'
    | '/c/$slug/purchase/pending'
    | '/c/$slug/purchase/suppliers'
    | '/c/$slug/reports/accounts'
    | '/c/$slug/reports/departments'
    | '/c/$slug/reports/employees'
    | '/c/$slug/reports/leads'
    | '/c/$slug/reports/projects'
    | '/c/$slug/reports/tasks'
    | '/c/$slug/settings/appearance'
    | '/c/$slug/settings/audit'
    | '/c/$slug/settings/company'
    | '/c/$slug/settings/departments'
    | '/c/$slug/settings/fields'
    | '/c/$slug/settings/invoicing'
    | '/c/$slug/settings/project-templates'
    | '/c/$slug/settings/roles'
    | '/c/$slug/settings/stock'
    | '/c/$slug/settings/workflow'
    | '/c/$slug/stock/balance'
    | '/c/$slug/stock/items'
    | '/c/$slug/stock/movements'
    | '/c/$slug/accounts'
    | '/c/$slug/clients'
    | '/c/$slug/departments'
    | '/c/$slug/invoicing'
    | '/c/$slug/leads'
    | '/c/$slug/projects'
    | '/c/$slug/purchase'
    | '/c/$slug/reports'
    | '/c/$slug/settings'
    | '/c/$slug/stock'
    | '/c/$slug/leads/stage/$stage'
    | '/c/$slug/purchase/suppliers/$supplierId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/c/$slug'
    | '/admin/'
    | '/api/storage/delete'
    | '/c/$slug/_app'
    | '/c/$slug/auth'
    | '/c/$slug/_app/accounts'
    | '/c/$slug/_app/clients'
    | '/c/$slug/_app/dashboard'
    | '/c/$slug/_app/departments'
    | '/c/$slug/_app/employees'
    | '/c/$slug/_app/expenses'
    | '/c/$slug/_app/invoicing'
    | '/c/$slug/_app/leads'
    | '/c/$slug/_app/projects'
    | '/c/$slug/_app/purchase'
    | '/c/$slug/_app/reports'
    | '/c/$slug/_app/settings'
    | '/c/$slug/_app/stock'
    | '/c/$slug/_app/tasks'
    | '/api/public/c/$slug/logo'
    | '/api/public/c/$slug/manifest.webmanifest'
    | '/c/$slug/_app/accounts/book'
    | '/c/$slug/_app/accounts/expenses'
    | '/c/$slug/_app/accounts/income'
    | '/c/$slug/_app/accounts/ledger'
    | '/c/$slug/_app/accounts/pending'
    | '/c/$slug/_app/clients/$clientId'
    | '/c/$slug/_app/departments/$deptId'
    | '/c/$slug/_app/invoicing/invoices'
    | '/c/$slug/_app/invoicing/payments'
    | '/c/$slug/_app/invoicing/pending'
    | '/c/$slug/_app/invoicing/quotations'
    | '/c/$slug/_app/leads/$leadId'
    | '/c/$slug/_app/projects/$projectId'
    | '/c/$slug/_app/purchase/orders'
    | '/c/$slug/_app/purchase/payments'
    | '/c/$slug/_app/purchase/pending'
    | '/c/$slug/_app/purchase/suppliers'
    | '/c/$slug/_app/reports/accounts'
    | '/c/$slug/_app/reports/departments'
    | '/c/$slug/_app/reports/employees'
    | '/c/$slug/_app/reports/leads'
    | '/c/$slug/_app/reports/projects'
    | '/c/$slug/_app/reports/tasks'
    | '/c/$slug/_app/settings/appearance'
    | '/c/$slug/_app/settings/audit'
    | '/c/$slug/_app/settings/company'
    | '/c/$slug/_app/settings/departments'
    | '/c/$slug/_app/settings/fields'
    | '/c/$slug/_app/settings/invoicing'
    | '/c/$slug/_app/settings/project-templates'
    | '/c/$slug/_app/settings/roles'
    | '/c/$slug/_app/settings/stock'
    | '/c/$slug/_app/settings/workflow'
    | '/c/$slug/_app/stock/balance'
    | '/c/$slug/_app/stock/items'
    | '/c/$slug/_app/stock/movements'
    | '/c/$slug/_app/accounts/'
    | '/c/$slug/_app/clients/'
    | '/c/$slug/_app/departments/'
    | '/c/$slug/_app/invoicing/'
    | '/c/$slug/_app/leads/'
    | '/c/$slug/_app/projects/'
    | '/c/$slug/_app/purchase/'
    | '/c/$slug/_app/reports/'
    | '/c/$slug/_app/settings/'
    | '/c/$slug/_app/stock/'
    | '/c/$slug/_app/leads/stage/$stage'
    | '/c/$slug/_app/purchase/suppliers/$supplierId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CSlugRoute: typeof CSlugRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  ApiStorageDeleteRoute: typeof ApiStorageDeleteRoute
  ApiPublicCSlugLogoRoute: typeof ApiPublicCSlugLogoRoute
  ApiPublicCSlugManifestDotwebmanifestRoute: typeof ApiPublicCSlugManifestDotwebmanifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/auth': {
      id: '/c/$slug/auth'
      path: '/auth'
      fullPath: '/c/$slug/auth'
      preLoaderRoute: typeof CSlugAuthRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/_app': {
      id: '/c/$slug/_app'
      path: ''
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugAppRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/api/storage/delete': {
      id: '/api/storage/delete'
      path: '/api/storage/delete'
      fullPath: '/api/storage/delete'
      preLoaderRoute: typeof ApiStorageDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/_app/tasks': {
      id: '/c/$slug/_app/tasks'
      path: '/tasks'
      fullPath: '/c/$slug/tasks'
      preLoaderRoute: typeof CSlugAppTasksRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/stock': {
      id: '/c/$slug/_app/stock'
      path: '/stock'
      fullPath: '/c/$slug/stock'
      preLoaderRoute: typeof CSlugAppStockRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/settings': {
      id: '/c/$slug/_app/settings'
      path: '/settings'
      fullPath: '/c/$slug/settings'
      preLoaderRoute: typeof CSlugAppSettingsRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/reports': {
      id: '/c/$slug/_app/reports'
      path: '/reports'
      fullPath: '/c/$slug/reports'
      preLoaderRoute: typeof CSlugAppReportsRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/purchase': {
      id: '/c/$slug/_app/purchase'
      path: '/purchase'
      fullPath: '/c/$slug/purchase'
      preLoaderRoute: typeof CSlugAppPurchaseRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/projects': {
      id: '/c/$slug/_app/projects'
      path: '/projects'
      fullPath: '/c/$slug/projects'
      preLoaderRoute: typeof CSlugAppProjectsRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/leads': {
      id: '/c/$slug/_app/leads'
      path: '/leads'
      fullPath: '/c/$slug/leads'
      preLoaderRoute: typeof CSlugAppLeadsRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/invoicing': {
      id: '/c/$slug/_app/invoicing'
      path: '/invoicing'
      fullPath: '/c/$slug/invoicing'
      preLoaderRoute: typeof CSlugAppInvoicingRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/expenses': {
      id: '/c/$slug/_app/expenses'
      path: '/expenses'
      fullPath: '/c/$slug/expenses'
      preLoaderRoute: typeof CSlugAppExpensesRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/employees': {
      id: '/c/$slug/_app/employees'
      path: '/employees'
      fullPath: '/c/$slug/employees'
      preLoaderRoute: typeof CSlugAppEmployeesRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/departments': {
      id: '/c/$slug/_app/departments'
      path: '/departments'
      fullPath: '/c/$slug/departments'
      preLoaderRoute: typeof CSlugAppDepartmentsRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/dashboard': {
      id: '/c/$slug/_app/dashboard'
      path: '/dashboard'
      fullPath: '/c/$slug/dashboard'
      preLoaderRoute: typeof CSlugAppDashboardRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/clients': {
      id: '/c/$slug/_app/clients'
      path: '/clients'
      fullPath: '/c/$slug/clients'
      preLoaderRoute: typeof CSlugAppClientsRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/accounts': {
      id: '/c/$slug/_app/accounts'
      path: '/accounts'
      fullPath: '/c/$slug/accounts'
      preLoaderRoute: typeof CSlugAppAccountsRouteImport
      parentRoute: typeof CSlugAppRoute
    }
    '/c/$slug/_app/stock/': {
      id: '/c/$slug/_app/stock/'
      path: '/'
      fullPath: '/c/$slug/stock/'
      preLoaderRoute: typeof CSlugAppStockIndexRouteImport
      parentRoute: typeof CSlugAppStockRoute
    }
    '/c/$slug/_app/settings/': {
      id: '/c/$slug/_app/settings/'
      path: '/'
      fullPath: '/c/$slug/settings/'
      preLoaderRoute: typeof CSlugAppSettingsIndexRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/reports/': {
      id: '/c/$slug/_app/reports/'
      path: '/'
      fullPath: '/c/$slug/reports/'
      preLoaderRoute: typeof CSlugAppReportsIndexRouteImport
      parentRoute: typeof CSlugAppReportsRoute
    }
    '/c/$slug/_app/purchase/': {
      id: '/c/$slug/_app/purchase/'
      path: '/'
      fullPath: '/c/$slug/purchase/'
      preLoaderRoute: typeof CSlugAppPurchaseIndexRouteImport
      parentRoute: typeof CSlugAppPurchaseRoute
    }
    '/c/$slug/_app/projects/': {
      id: '/c/$slug/_app/projects/'
      path: '/'
      fullPath: '/c/$slug/projects/'
      preLoaderRoute: typeof CSlugAppProjectsIndexRouteImport
      parentRoute: typeof CSlugAppProjectsRoute
    }
    '/c/$slug/_app/leads/': {
      id: '/c/$slug/_app/leads/'
      path: '/'
      fullPath: '/c/$slug/leads/'
      preLoaderRoute: typeof CSlugAppLeadsIndexRouteImport
      parentRoute: typeof CSlugAppLeadsRoute
    }
    '/c/$slug/_app/invoicing/': {
      id: '/c/$slug/_app/invoicing/'
      path: '/'
      fullPath: '/c/$slug/invoicing/'
      preLoaderRoute: typeof CSlugAppInvoicingIndexRouteImport
      parentRoute: typeof CSlugAppInvoicingRoute
    }
    '/c/$slug/_app/departments/': {
      id: '/c/$slug/_app/departments/'
      path: '/'
      fullPath: '/c/$slug/departments/'
      preLoaderRoute: typeof CSlugAppDepartmentsIndexRouteImport
      parentRoute: typeof CSlugAppDepartmentsRoute
    }
    '/c/$slug/_app/clients/': {
      id: '/c/$slug/_app/clients/'
      path: '/'
      fullPath: '/c/$slug/clients/'
      preLoaderRoute: typeof CSlugAppClientsIndexRouteImport
      parentRoute: typeof CSlugAppClientsRoute
    }
    '/c/$slug/_app/accounts/': {
      id: '/c/$slug/_app/accounts/'
      path: '/'
      fullPath: '/c/$slug/accounts/'
      preLoaderRoute: typeof CSlugAppAccountsIndexRouteImport
      parentRoute: typeof CSlugAppAccountsRoute
    }
    '/c/$slug/_app/stock/movements': {
      id: '/c/$slug/_app/stock/movements'
      path: '/movements'
      fullPath: '/c/$slug/stock/movements'
      preLoaderRoute: typeof CSlugAppStockMovementsRouteImport
      parentRoute: typeof CSlugAppStockRoute
    }
    '/c/$slug/_app/stock/items': {
      id: '/c/$slug/_app/stock/items'
      path: '/items'
      fullPath: '/c/$slug/stock/items'
      preLoaderRoute: typeof CSlugAppStockItemsRouteImport
      parentRoute: typeof CSlugAppStockRoute
    }
    '/c/$slug/_app/stock/balance': {
      id: '/c/$slug/_app/stock/balance'
      path: '/balance'
      fullPath: '/c/$slug/stock/balance'
      preLoaderRoute: typeof CSlugAppStockBalanceRouteImport
      parentRoute: typeof CSlugAppStockRoute
    }
    '/c/$slug/_app/settings/workflow': {
      id: '/c/$slug/_app/settings/workflow'
      path: '/workflow'
      fullPath: '/c/$slug/settings/workflow'
      preLoaderRoute: typeof CSlugAppSettingsWorkflowRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/settings/stock': {
      id: '/c/$slug/_app/settings/stock'
      path: '/stock'
      fullPath: '/c/$slug/settings/stock'
      preLoaderRoute: typeof CSlugAppSettingsStockRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/settings/roles': {
      id: '/c/$slug/_app/settings/roles'
      path: '/roles'
      fullPath: '/c/$slug/settings/roles'
      preLoaderRoute: typeof CSlugAppSettingsRolesRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/settings/project-templates': {
      id: '/c/$slug/_app/settings/project-templates'
      path: '/project-templates'
      fullPath: '/c/$slug/settings/project-templates'
      preLoaderRoute: typeof CSlugAppSettingsProjectTemplatesRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/settings/invoicing': {
      id: '/c/$slug/_app/settings/invoicing'
      path: '/invoicing'
      fullPath: '/c/$slug/settings/invoicing'
      preLoaderRoute: typeof CSlugAppSettingsInvoicingRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/settings/fields': {
      id: '/c/$slug/_app/settings/fields'
      path: '/fields'
      fullPath: '/c/$slug/settings/fields'
      preLoaderRoute: typeof CSlugAppSettingsFieldsRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/settings/departments': {
      id: '/c/$slug/_app/settings/departments'
      path: '/departments'
      fullPath: '/c/$slug/settings/departments'
      preLoaderRoute: typeof CSlugAppSettingsDepartmentsRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/settings/company': {
      id: '/c/$slug/_app/settings/company'
      path: '/company'
      fullPath: '/c/$slug/settings/company'
      preLoaderRoute: typeof CSlugAppSettingsCompanyRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/settings/audit': {
      id: '/c/$slug/_app/settings/audit'
      path: '/audit'
      fullPath: '/c/$slug/settings/audit'
      preLoaderRoute: typeof CSlugAppSettingsAuditRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/settings/appearance': {
      id: '/c/$slug/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/c/$slug/settings/appearance'
      preLoaderRoute: typeof CSlugAppSettingsAppearanceRouteImport
      parentRoute: typeof CSlugAppSettingsRoute
    }
    '/c/$slug/_app/reports/tasks': {
      id: '/c/$slug/_app/reports/tasks'
      path: '/tasks'
      fullPath: '/c/$slug/reports/tasks'
      preLoaderRoute: typeof CSlugAppReportsTasksRouteImport
      parentRoute: typeof CSlugAppReportsRoute
    }
    '/c/$slug/_app/reports/projects': {
      id: '/c/$slug/_app/reports/projects'
      path: '/projects'
      fullPath: '/c/$slug/reports/projects'
      preLoaderRoute: typeof CSlugAppReportsProjectsRouteImport
      parentRoute: typeof CSlugAppReportsRoute
    }
    '/c/$slug/_app/reports/leads': {
      id: '/c/$slug/_app/reports/leads'
      path: '/leads'
      fullPath: '/c/$slug/reports/leads'
      preLoaderRoute: typeof CSlugAppReportsLeadsRouteImport
      parentRoute: typeof CSlugAppReportsRoute
    }
    '/c/$slug/_app/reports/employees': {
      id: '/c/$slug/_app/reports/employees'
      path: '/employees'
      fullPath: '/c/$slug/reports/employees'
      preLoaderRoute: typeof CSlugAppReportsEmployeesRouteImport
      parentRoute: typeof CSlugAppReportsRoute
    }
    '/c/$slug/_app/reports/departments': {
      id: '/c/$slug/_app/reports/departments'
      path: '/departments'
      fullPath: '/c/$slug/reports/departments'
      preLoaderRoute: typeof CSlugAppReportsDepartmentsRouteImport
      parentRoute: typeof CSlugAppReportsRoute
    }
    '/c/$slug/_app/reports/accounts': {
      id: '/c/$slug/_app/reports/accounts'
      path: '/accounts'
      fullPath: '/c/$slug/reports/accounts'
      preLoaderRoute: typeof CSlugAppReportsAccountsRouteImport
      parentRoute: typeof CSlugAppReportsRoute
    }
    '/c/$slug/_app/purchase/suppliers': {
      id: '/c/$slug/_app/purchase/suppliers'
      path: '/suppliers'
      fullPath: '/c/$slug/purchase/suppliers'
      preLoaderRoute: typeof CSlugAppPurchaseSuppliersRouteImport
      parentRoute: typeof CSlugAppPurchaseRoute
    }
    '/c/$slug/_app/purchase/pending': {
      id: '/c/$slug/_app/purchase/pending'
      path: '/pending'
      fullPath: '/c/$slug/purchase/pending'
      preLoaderRoute: typeof CSlugAppPurchasePendingRouteImport
      parentRoute: typeof CSlugAppPurchaseRoute
    }
    '/c/$slug/_app/purchase/payments': {
      id: '/c/$slug/_app/purchase/payments'
      path: '/payments'
      fullPath: '/c/$slug/purchase/payments'
      preLoaderRoute: typeof CSlugAppPurchasePaymentsRouteImport
      parentRoute: typeof CSlugAppPurchaseRoute
    }
    '/c/$slug/_app/purchase/orders': {
      id: '/c/$slug/_app/purchase/orders'
      path: '/orders'
      fullPath: '/c/$slug/purchase/orders'
      preLoaderRoute: typeof CSlugAppPurchaseOrdersRouteImport
      parentRoute: typeof CSlugAppPurchaseRoute
    }
    '/c/$slug/_app/projects/$projectId': {
      id: '/c/$slug/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/c/$slug/projects/$projectId'
      preLoaderRoute: typeof CSlugAppProjectsProjectIdRouteImport
      parentRoute: typeof CSlugAppProjectsRoute
    }
    '/c/$slug/_app/leads/$leadId': {
      id: '/c/$slug/_app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/c/$slug/leads/$leadId'
      preLoaderRoute: typeof CSlugAppLeadsLeadIdRouteImport
      parentRoute: typeof CSlugAppLeadsRoute
    }
    '/c/$slug/_app/invoicing/quotations': {
      id: '/c/$slug/_app/invoicing/quotations'
      path: '/quotations'
      fullPath: '/c/$slug/invoicing/quotations'
      preLoaderRoute: typeof CSlugAppInvoicingQuotationsRouteImport
      parentRoute: typeof CSlugAppInvoicingRoute
    }
    '/c/$slug/_app/invoicing/pending': {
      id: '/c/$slug/_app/invoicing/pending'
      path: '/pending'
      fullPath: '/c/$slug/invoicing/pending'
      preLoaderRoute: typeof CSlugAppInvoicingPendingRouteImport
      parentRoute: typeof CSlugAppInvoicingRoute
    }
    '/c/$slug/_app/invoicing/payments': {
      id: '/c/$slug/_app/invoicing/payments'
      path: '/payments'
      fullPath: '/c/$slug/invoicing/payments'
      preLoaderRoute: typeof CSlugAppInvoicingPaymentsRouteImport
      parentRoute: typeof CSlugAppInvoicingRoute
    }
    '/c/$slug/_app/invoicing/invoices': {
      id: '/c/$slug/_app/invoicing/invoices'
      path: '/invoices'
      fullPath: '/c/$slug/invoicing/invoices'
      preLoaderRoute: typeof CSlugAppInvoicingInvoicesRouteImport
      parentRoute: typeof CSlugAppInvoicingRoute
    }
    '/c/$slug/_app/departments/$deptId': {
      id: '/c/$slug/_app/departments/$deptId'
      path: '/$deptId'
      fullPath: '/c/$slug/departments/$deptId'
      preLoaderRoute: typeof CSlugAppDepartmentsDeptIdRouteImport
      parentRoute: typeof CSlugAppDepartmentsRoute
    }
    '/c/$slug/_app/clients/$clientId': {
      id: '/c/$slug/_app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/c/$slug/clients/$clientId'
      preLoaderRoute: typeof CSlugAppClientsClientIdRouteImport
      parentRoute: typeof CSlugAppClientsRoute
    }
    '/c/$slug/_app/accounts/pending': {
      id: '/c/$slug/_app/accounts/pending'
      path: '/pending'
      fullPath: '/c/$slug/accounts/pending'
      preLoaderRoute: typeof CSlugAppAccountsPendingRouteImport
      parentRoute: typeof CSlugAppAccountsRoute
    }
    '/c/$slug/_app/accounts/ledger': {
      id: '/c/$slug/_app/accounts/ledger'
      path: '/ledger'
      fullPath: '/c/$slug/accounts/ledger'
      preLoaderRoute: typeof CSlugAppAccountsLedgerRouteImport
      parentRoute: typeof CSlugAppAccountsRoute
    }
    '/c/$slug/_app/accounts/income': {
      id: '/c/$slug/_app/accounts/income'
      path: '/income'
      fullPath: '/c/$slug/accounts/income'
      preLoaderRoute: typeof CSlugAppAccountsIncomeRouteImport
      parentRoute: typeof CSlugAppAccountsRoute
    }
    '/c/$slug/_app/accounts/expenses': {
      id: '/c/$slug/_app/accounts/expenses'
      path: '/expenses'
      fullPath: '/c/$slug/accounts/expenses'
      preLoaderRoute: typeof CSlugAppAccountsExpensesRouteImport
      parentRoute: typeof CSlugAppAccountsRoute
    }
    '/c/$slug/_app/accounts/book': {
      id: '/c/$slug/_app/accounts/book'
      path: '/book'
      fullPath: '/c/$slug/accounts/book'
      preLoaderRoute: typeof CSlugAppAccountsBookRouteImport
      parentRoute: typeof CSlugAppAccountsRoute
    }
    '/api/public/c/$slug/manifest.webmanifest': {
      id: '/api/public/c/$slug/manifest.webmanifest'
      path: '/api/public/c/$slug/manifest.webmanifest'
      fullPath: '/api/public/c/$slug/manifest.webmanifest'
      preLoaderRoute: typeof ApiPublicCSlugManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/c/$slug/logo': {
      id: '/api/public/c/$slug/logo'
      path: '/api/public/c/$slug/logo'
      fullPath: '/api/public/c/$slug/logo'
      preLoaderRoute: typeof ApiPublicCSlugLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug/_app/purchase/suppliers/$supplierId': {
      id: '/c/$slug/_app/purchase/suppliers/$supplierId'
      path: '/$supplierId'
      fullPath: '/c/$slug/purchase/suppliers/$supplierId'
      preLoaderRoute: typeof CSlugAppPurchaseSuppliersSupplierIdRouteImport
      parentRoute: typeof CSlugAppPurchaseSuppliersRoute
    }
    '/c/$slug/_app/leads/stage/$stage': {
      id: '/c/$slug/_app/leads/stage/$stage'
      path: '/stage/$stage'
      fullPath: '/c/$slug/leads/stage/$stage'
      preLoaderRoute: typeof CSlugAppLeadsStageStageRouteImport
      parentRoute: typeof CSlugAppLeadsRoute
    }
  }
}

interface CSlugAppAccountsRouteChildren {
  CSlugAppAccountsBookRoute: typeof CSlugAppAccountsBookRoute
  CSlugAppAccountsExpensesRoute: typeof CSlugAppAccountsExpensesRoute
  CSlugAppAccountsIncomeRoute: typeof CSlugAppAccountsIncomeRoute
  CSlugAppAccountsLedgerRoute: typeof CSlugAppAccountsLedgerRoute
  CSlugAppAccountsPendingRoute: typeof CSlugAppAccountsPendingRoute
  CSlugAppAccountsIndexRoute: typeof CSlugAppAccountsIndexRoute
}

const CSlugAppAccountsRouteChildren: CSlugAppAccountsRouteChildren = {
  CSlugAppAccountsBookRoute: CSlugAppAccountsBookRoute,
  CSlugAppAccountsExpensesRoute: CSlugAppAccountsExpensesRoute,
  CSlugAppAccountsIncomeRoute: CSlugAppAccountsIncomeRoute,
  CSlugAppAccountsLedgerRoute: CSlugAppAccountsLedgerRoute,
  CSlugAppAccountsPendingRoute: CSlugAppAccountsPendingRoute,
  CSlugAppAccountsIndexRoute: CSlugAppAccountsIndexRoute,
}

const CSlugAppAccountsRouteWithChildren =
  CSlugAppAccountsRoute._addFileChildren(CSlugAppAccountsRouteChildren)

interface CSlugAppClientsRouteChildren {
  CSlugAppClientsClientIdRoute: typeof CSlugAppClientsClientIdRoute
  CSlugAppClientsIndexRoute: typeof CSlugAppClientsIndexRoute
}

const CSlugAppClientsRouteChildren: CSlugAppClientsRouteChildren = {
  CSlugAppClientsClientIdRoute: CSlugAppClientsClientIdRoute,
  CSlugAppClientsIndexRoute: CSlugAppClientsIndexRoute,
}

const CSlugAppClientsRouteWithChildren = CSlugAppClientsRoute._addFileChildren(
  CSlugAppClientsRouteChildren,
)

interface CSlugAppDepartmentsRouteChildren {
  CSlugAppDepartmentsDeptIdRoute: typeof CSlugAppDepartmentsDeptIdRoute
  CSlugAppDepartmentsIndexRoute: typeof CSlugAppDepartmentsIndexRoute
}

const CSlugAppDepartmentsRouteChildren: CSlugAppDepartmentsRouteChildren = {
  CSlugAppDepartmentsDeptIdRoute: CSlugAppDepartmentsDeptIdRoute,
  CSlugAppDepartmentsIndexRoute: CSlugAppDepartmentsIndexRoute,
}

const CSlugAppDepartmentsRouteWithChildren =
  CSlugAppDepartmentsRoute._addFileChildren(CSlugAppDepartmentsRouteChildren)

interface CSlugAppInvoicingRouteChildren {
  CSlugAppInvoicingInvoicesRoute: typeof CSlugAppInvoicingInvoicesRoute
  CSlugAppInvoicingPaymentsRoute: typeof CSlugAppInvoicingPaymentsRoute
  CSlugAppInvoicingPendingRoute: typeof CSlugAppInvoicingPendingRoute
  CSlugAppInvoicingQuotationsRoute: typeof CSlugAppInvoicingQuotationsRoute
  CSlugAppInvoicingIndexRoute: typeof CSlugAppInvoicingIndexRoute
}

const CSlugAppInvoicingRouteChildren: CSlugAppInvoicingRouteChildren = {
  CSlugAppInvoicingInvoicesRoute: CSlugAppInvoicingInvoicesRoute,
  CSlugAppInvoicingPaymentsRoute: CSlugAppInvoicingPaymentsRoute,
  CSlugAppInvoicingPendingRoute: CSlugAppInvoicingPendingRoute,
  CSlugAppInvoicingQuotationsRoute: CSlugAppInvoicingQuotationsRoute,
  CSlugAppInvoicingIndexRoute: CSlugAppInvoicingIndexRoute,
}

const CSlugAppInvoicingRouteWithChildren =
  CSlugAppInvoicingRoute._addFileChildren(CSlugAppInvoicingRouteChildren)

interface CSlugAppLeadsRouteChildren {
  CSlugAppLeadsLeadIdRoute: typeof CSlugAppLeadsLeadIdRoute
  CSlugAppLeadsIndexRoute: typeof CSlugAppLeadsIndexRoute
  CSlugAppLeadsStageStageRoute: typeof CSlugAppLeadsStageStageRoute
}

const CSlugAppLeadsRouteChildren: CSlugAppLeadsRouteChildren = {
  CSlugAppLeadsLeadIdRoute: CSlugAppLeadsLeadIdRoute,
  CSlugAppLeadsIndexRoute: CSlugAppLeadsIndexRoute,
  CSlugAppLeadsStageStageRoute: CSlugAppLeadsStageStageRoute,
}

const CSlugAppLeadsRouteWithChildren = CSlugAppLeadsRoute._addFileChildren(
  CSlugAppLeadsRouteChildren,
)

interface CSlugAppProjectsRouteChildren {
  CSlugAppProjectsProjectIdRoute: typeof CSlugAppProjectsProjectIdRoute
  CSlugAppProjectsIndexRoute: typeof CSlugAppProjectsIndexRoute
}

const CSlugAppProjectsRouteChildren: CSlugAppProjectsRouteChildren = {
  CSlugAppProjectsProjectIdRoute: CSlugAppProjectsProjectIdRoute,
  CSlugAppProjectsIndexRoute: CSlugAppProjectsIndexRoute,
}

const CSlugAppProjectsRouteWithChildren =
  CSlugAppProjectsRoute._addFileChildren(CSlugAppProjectsRouteChildren)

interface CSlugAppPurchaseSuppliersRouteChildren {
  CSlugAppPurchaseSuppliersSupplierIdRoute: typeof CSlugAppPurchaseSuppliersSupplierIdRoute
}

const CSlugAppPurchaseSuppliersRouteChildren: CSlugAppPurchaseSuppliersRouteChildren =
  {
    CSlugAppPurchaseSuppliersSupplierIdRoute:
      CSlugAppPurchaseSuppliersSupplierIdRoute,
  }

const CSlugAppPurchaseSuppliersRouteWithChildren =
  CSlugAppPurchaseSuppliersRoute._addFileChildren(
    CSlugAppPurchaseSuppliersRouteChildren,
  )

interface CSlugAppPurchaseRouteChildren {
  CSlugAppPurchaseOrdersRoute: typeof CSlugAppPurchaseOrdersRoute
  CSlugAppPurchasePaymentsRoute: typeof CSlugAppPurchasePaymentsRoute
  CSlugAppPurchasePendingRoute: typeof CSlugAppPurchasePendingRoute
  CSlugAppPurchaseSuppliersRoute: typeof CSlugAppPurchaseSuppliersRouteWithChildren
  CSlugAppPurchaseIndexRoute: typeof CSlugAppPurchaseIndexRoute
}

const CSlugAppPurchaseRouteChildren: CSlugAppPurchaseRouteChildren = {
  CSlugAppPurchaseOrdersRoute: CSlugAppPurchaseOrdersRoute,
  CSlugAppPurchasePaymentsRoute: CSlugAppPurchasePaymentsRoute,
  CSlugAppPurchasePendingRoute: CSlugAppPurchasePendingRoute,
  CSlugAppPurchaseSuppliersRoute: CSlugAppPurchaseSuppliersRouteWithChildren,
  CSlugAppPurchaseIndexRoute: CSlugAppPurchaseIndexRoute,
}

const CSlugAppPurchaseRouteWithChildren =
  CSlugAppPurchaseRoute._addFileChildren(CSlugAppPurchaseRouteChildren)

interface CSlugAppReportsRouteChildren {
  CSlugAppReportsAccountsRoute: typeof CSlugAppReportsAccountsRoute
  CSlugAppReportsDepartmentsRoute: typeof CSlugAppReportsDepartmentsRoute
  CSlugAppReportsEmployeesRoute: typeof CSlugAppReportsEmployeesRoute
  CSlugAppReportsLeadsRoute: typeof CSlugAppReportsLeadsRoute
  CSlugAppReportsProjectsRoute: typeof CSlugAppReportsProjectsRoute
  CSlugAppReportsTasksRoute: typeof CSlugAppReportsTasksRoute
  CSlugAppReportsIndexRoute: typeof CSlugAppReportsIndexRoute
}

const CSlugAppReportsRouteChildren: CSlugAppReportsRouteChildren = {
  CSlugAppReportsAccountsRoute: CSlugAppReportsAccountsRoute,
  CSlugAppReportsDepartmentsRoute: CSlugAppReportsDepartmentsRoute,
  CSlugAppReportsEmployeesRoute: CSlugAppReportsEmployeesRoute,
  CSlugAppReportsLeadsRoute: CSlugAppReportsLeadsRoute,
  CSlugAppReportsProjectsRoute: CSlugAppReportsProjectsRoute,
  CSlugAppReportsTasksRoute: CSlugAppReportsTasksRoute,
  CSlugAppReportsIndexRoute: CSlugAppReportsIndexRoute,
}

const CSlugAppReportsRouteWithChildren = CSlugAppReportsRoute._addFileChildren(
  CSlugAppReportsRouteChildren,
)

interface CSlugAppSettingsRouteChildren {
  CSlugAppSettingsAppearanceRoute: typeof CSlugAppSettingsAppearanceRoute
  CSlugAppSettingsAuditRoute: typeof CSlugAppSettingsAuditRoute
  CSlugAppSettingsCompanyRoute: typeof CSlugAppSettingsCompanyRoute
  CSlugAppSettingsDepartmentsRoute: typeof CSlugAppSettingsDepartmentsRoute
  CSlugAppSettingsFieldsRoute: typeof CSlugAppSettingsFieldsRoute
  CSlugAppSettingsInvoicingRoute: typeof CSlugAppSettingsInvoicingRoute
  CSlugAppSettingsProjectTemplatesRoute: typeof CSlugAppSettingsProjectTemplatesRoute
  CSlugAppSettingsRolesRoute: typeof CSlugAppSettingsRolesRoute
  CSlugAppSettingsStockRoute: typeof CSlugAppSettingsStockRoute
  CSlugAppSettingsWorkflowRoute: typeof CSlugAppSettingsWorkflowRoute
  CSlugAppSettingsIndexRoute: typeof CSlugAppSettingsIndexRoute
}

const CSlugAppSettingsRouteChildren: CSlugAppSettingsRouteChildren = {
  CSlugAppSettingsAppearanceRoute: CSlugAppSettingsAppearanceRoute,
  CSlugAppSettingsAuditRoute: CSlugAppSettingsAuditRoute,
  CSlugAppSettingsCompanyRoute: CSlugAppSettingsCompanyRoute,
  CSlugAppSettingsDepartmentsRoute: CSlugAppSettingsDepartmentsRoute,
  CSlugAppSettingsFieldsRoute: CSlugAppSettingsFieldsRoute,
  CSlugAppSettingsInvoicingRoute: CSlugAppSettingsInvoicingRoute,
  CSlugAppSettingsProjectTemplatesRoute: CSlugAppSettingsProjectTemplatesRoute,
  CSlugAppSettingsRolesRoute: CSlugAppSettingsRolesRoute,
  CSlugAppSettingsStockRoute: CSlugAppSettingsStockRoute,
  CSlugAppSettingsWorkflowRoute: CSlugAppSettingsWorkflowRoute,
  CSlugAppSettingsIndexRoute: CSlugAppSettingsIndexRoute,
}

const CSlugAppSettingsRouteWithChildren =
  CSlugAppSettingsRoute._addFileChildren(CSlugAppSettingsRouteChildren)

interface CSlugAppStockRouteChildren {
  CSlugAppStockBalanceRoute: typeof CSlugAppStockBalanceRoute
  CSlugAppStockItemsRoute: typeof CSlugAppStockItemsRoute
  CSlugAppStockMovementsRoute: typeof CSlugAppStockMovementsRoute
  CSlugAppStockIndexRoute: typeof CSlugAppStockIndexRoute
}

const CSlugAppStockRouteChildren: CSlugAppStockRouteChildren = {
  CSlugAppStockBalanceRoute: CSlugAppStockBalanceRoute,
  CSlugAppStockItemsRoute: CSlugAppStockItemsRoute,
  CSlugAppStockMovementsRoute: CSlugAppStockMovementsRoute,
  CSlugAppStockIndexRoute: CSlugAppStockIndexRoute,
}

const CSlugAppStockRouteWithChildren = CSlugAppStockRoute._addFileChildren(
  CSlugAppStockRouteChildren,
)

interface CSlugAppRouteChildren {
  CSlugAppAccountsRoute: typeof CSlugAppAccountsRouteWithChildren
  CSlugAppClientsRoute: typeof CSlugAppClientsRouteWithChildren
  CSlugAppDashboardRoute: typeof CSlugAppDashboardRoute
  CSlugAppDepartmentsRoute: typeof CSlugAppDepartmentsRouteWithChildren
  CSlugAppEmployeesRoute: typeof CSlugAppEmployeesRoute
  CSlugAppExpensesRoute: typeof CSlugAppExpensesRoute
  CSlugAppInvoicingRoute: typeof CSlugAppInvoicingRouteWithChildren
  CSlugAppLeadsRoute: typeof CSlugAppLeadsRouteWithChildren
  CSlugAppProjectsRoute: typeof CSlugAppProjectsRouteWithChildren
  CSlugAppPurchaseRoute: typeof CSlugAppPurchaseRouteWithChildren
  CSlugAppReportsRoute: typeof CSlugAppReportsRouteWithChildren
  CSlugAppSettingsRoute: typeof CSlugAppSettingsRouteWithChildren
  CSlugAppStockRoute: typeof CSlugAppStockRouteWithChildren
  CSlugAppTasksRoute: typeof CSlugAppTasksRoute
}

const CSlugAppRouteChildren: CSlugAppRouteChildren = {
  CSlugAppAccountsRoute: CSlugAppAccountsRouteWithChildren,
  CSlugAppClientsRoute: CSlugAppClientsRouteWithChildren,
  CSlugAppDashboardRoute: CSlugAppDashboardRoute,
  CSlugAppDepartmentsRoute: CSlugAppDepartmentsRouteWithChildren,
  CSlugAppEmployeesRoute: CSlugAppEmployeesRoute,
  CSlugAppExpensesRoute: CSlugAppExpensesRoute,
  CSlugAppInvoicingRoute: CSlugAppInvoicingRouteWithChildren,
  CSlugAppLeadsRoute: CSlugAppLeadsRouteWithChildren,
  CSlugAppProjectsRoute: CSlugAppProjectsRouteWithChildren,
  CSlugAppPurchaseRoute: CSlugAppPurchaseRouteWithChildren,
  CSlugAppReportsRoute: CSlugAppReportsRouteWithChildren,
  CSlugAppSettingsRoute: CSlugAppSettingsRouteWithChildren,
  CSlugAppStockRoute: CSlugAppStockRouteWithChildren,
  CSlugAppTasksRoute: CSlugAppTasksRoute,
}

const CSlugAppRouteWithChildren = CSlugAppRoute._addFileChildren(
  CSlugAppRouteChildren,
)

interface CSlugRouteChildren {
  CSlugAppRoute: typeof CSlugAppRouteWithChildren
  CSlugAuthRoute: typeof CSlugAuthRoute
}

const CSlugRouteChildren: CSlugRouteChildren = {
  CSlugAppRoute: CSlugAppRouteWithChildren,
  CSlugAuthRoute: CSlugAuthRoute,
}

const CSlugRouteWithChildren = CSlugRoute._addFileChildren(CSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CSlugRoute: CSlugRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  ApiStorageDeleteRoute: ApiStorageDeleteRoute,
  ApiPublicCSlugLogoRoute: ApiPublicCSlugLogoRoute,
  ApiPublicCSlugManifestDotwebmanifestRoute:
    ApiPublicCSlugManifestDotwebmanifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
